#!/usr/bin/env sh

# ##################################################### #
# See the hotkey explanation at the bottom of file	#
# to understand definitions				#
# ##################################################### #

## fullscreen current window
ctrl + cmd - f : yabai -m window --grid 1:1:0:0:1:1

## Center current window
ctrl + alt - c : yabai -m query --displays --display | grep -o '"w":[0-9]*' | cut -d':' -f2 | read display_width && \
                 yabai -m query --displays --display | grep -o '"h":[0-9]*' | cut -d':' -f2 | read display_height && \
                 yabai -m query --windows --window | grep -o '"w":[0-9]*' | cut -d':' -f2 | read window_width && \
                 yabai -m query --windows --window | grep -o '"h":[0-9]*' | cut -d':' -f2 | read window_height && \
                 new_x=$(( (display_width - window_width) / 2 )) && \
                 new_y=$(( (display_height - window_height) / 2 )) && \
                 yabai -m window --move abs:$new_x:$new_y

# display_width=$(echo $display_info | grep -o '"w":[0-9]*' | cut -d':' -f2)
# display_height=$(echo $display_info | grep -o '"h":[0-9]*' | cut -d':' -f2)
# 
# window_info=$(yabai -m query --windows --window)
# window_width=$(echo $window_info | grep -o '"w":[0-9]*' | cut -d':' -f2)
# window_height=$(echo $window_info | grep -o '"h":[0-9]*' | cut -d':' -f2)
# 
# new_x=$(( (display_width - window_width) / 2 ))
# new_y=$(( (display_height - window_height) / 2 ))
# 
# yabai -m window --move abs:$new_x:$new_y

## halves
### left half
ctrl + alt - left : yabai -m window --grid 1:2:0:0:1:1
### right half
ctrl + alt - right : yabai -m window --grid 1:2:1:0:1:1

### thirds
#### left third
#yabai -m window --grid 1:3:0:0:1:1
#### middle third
#yabai -m window --grid 1:3:1:0:1:1
#### right third
#yabai -m window --grid 1:3:2:0:1:1

## quarters
### top-left
ctrl + alt - u : yabai -m window --grid 2:2:0:0:1:1
### top-right
ctrl + alt - i : yabai -m window --grid 2:2:1:0:1:1
### bottom-left
ctrl + alt - j : yabai -m window --grid 2:2:0:1:1:1
### bottom-right
ctrl + alt - k : yabai -m window --grid 2:2:1:1:1:1

# ################################################################ #
# Window Focusing                                                  #
# ################################################################ #

# Browser
hyper - b : yabai -m window --focus $(yabai -m query --windows | jq -r '.[] | select(.app == "Google Chrome") | .id' | awk 'NR')

# Terminal
hyper - t : yabai -m window --focus $( \
    yabai -m query --windows | jq -r '.[] | select(.app == "WezTerm") | .id' | awk 'NR==2' \
) \

# VSCode
hyper - c : yabai -m window --focus $( \
    yabai -m query --windows | jq -r '.[] | select(.app == "Code") | .id' | awk 'NR==2' \
) \

