#!/usr/bin/env sh
# ##################################################### #
# Window Management 					#
# ##################################################### #

# Send window to target space
ctrl + cmd + shift - 1 : yabai -m window --space 1
ctrl + cmd + shift - 2 : yabai -m window --space 2
ctrl + cmd + shift - 3 : yabai -m window --space 3
ctrl + cmd + shift - 4 : yabai -m window --space 4
ctrl + cmd + shift - 5 : yabai -m window --space 5
ctrl + cmd + shift - 6 : yabai -m window --space 6

# ##################################################### #
# Floating Window Management 				#
# ##################################################### #

# fullscreen current window
ctrl + cmd - f : yabai -m window --grid 1:1:0:0:1:1

## Center current window
ctrl + alt - c : yabai -m query --displays --display | grep -o '"w":[0-9]*' | cut -d':' -f2 | read display_width && \
                 yabai -m query --displays --display | grep -o '"h":[0-9]*' | cut -d':' -f2 | read display_height && \
                 yabai -m query --windows --window | grep -o '"w":[0-9]*' | cut -d':' -f2 | read window_width && \
                 yabai -m query --windows --window | grep -o '"h":[0-9]*' | cut -d':' -f2 | read window_height && \
                 new_x=$(( (display_width - window_width) / 2 )) && \
                 new_y=$(( (display_height - window_height) / 2 )) && \
                 yabai -m window --move abs:$new_x:$new_y
## halves
### left half
ctrl + alt - left : yabai -m window --grid 1:2:0:0:1:1
### right half
ctrl + alt - right : yabai -m window --grid 1:2:1:0:1:1

## quarters
### top-left
ctrl + alt - u : yabai -m window --grid 2:2:0:0:1:1
### top-right
ctrl + alt - i : yabai -m window --grid 2:2:1:0:1:1
### bottom-left
ctrl + alt - j : yabai -m window --grid 2:2:0:1:1:1
### bottom-right
ctrl + alt - k : yabai -m window --grid 2:2:1:1:1:1

# ################################################################ #
# Window Focusing                                                  #
# ################################################################ #

# Browser
hyper - b : yabai -m window --focus $(yabai -m query --windows | jq -r '.[] | select(.app == "Google Chrome") | .id' | awk 'NR==2')

# Terminal
hyper - t : yabai -m window --focus $( \
    yabai -m query --windows | jq -r '.[] | select(.app == "WezTerm") | .id' | awk 'NR==2' \
) \

# VSCode
hyper - c : yabai -m window --focus $( \
    yabai -m query --windows | jq -r '.[] | select(.app == "Code") | .id' | awk 'NR==2' \
) \

# Test
hyper - a : open -a /Applications/'Google Chrome'.app
